-- DROP DATABASE state_spaces_db;
-- CREATE DATABASE state_spaces_db;
-- USE state_spaces_db;

DROP TABLE VENUE_AMENITY;
DROP TABLE VENUE;
DROP TABLE AMENITY;
DROP TABLE BUILDING;

CREATE TABLE BUILDING (
    building_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    building_name VARCHAR(255) NOT NULL,
    building_street VARCHAR(255),
    building_district VARCHAR(100),
    building_city VARCHAR(100),
    PRIMARY KEY (building_ID)
);

CREATE TABLE AMENITY (
    amenity_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    amenity_type VARCHAR(100),
    amenity_description TEXT,
    PRIMARY KEY (amenity_ID)
);

CREATE TABLE VENUE (
    venue_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    venue_name VARCHAR(255) NOT NULL,
    venue_type VARCHAR(100),
    venue_capacity INTEGER,
    venue_floor_area DECIMAL(10, 2),
    under_renovation BOOLEAN DEFAULT FALSE,
    
    -- FK from BUILDING
    building_ID INTEGER NOT NULL,
    
    PRIMARY KEY (venue_ID),
    
    CONSTRAINT fk_venue_building
        FOREIGN KEY (building_ID)
        REFERENCES BUILDING (building_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE VENUE_AMENITY (
    venueamenity_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    venueamenity_quantity INTEGER DEFAULT 1,
    
    -- FK from VENUE
    venue_ID INTEGER NOT NULL,
    
    -- FK from AMENITY
    amenity_ID INTEGER,
    
    PRIMARY KEY (venueamenity_ID),
    
    CONSTRAINT fk_venueamenity_venue
        FOREIGN KEY (venue_ID)
        REFERENCES VENUE (venue_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
        
    CONSTRAINT fk_venueamenity_amenity
        FOREIGN KEY (amenity_ID)
        REFERENCES AMENITY (amenity_ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
        
    CONSTRAINT uq_amenity_id
        UNIQUE (amenity_ID)
);